import guiTools
import PyQt6.QtWidgets as qt
import PyQt6.QtGui as qt1
import PyQt6.QtCore as qt2
from .. import settings_handler


class SearchSettings(qt.QWidget):
    def __init__(self):
        super().__init__()
        layout = qt.QVBoxLayout(self)
        layout.setSpacing(15)
        layout.setContentsMargins(20, 20, 20, 20)
        font = qt1.QFont()
        font.setBold(True)
        layout.addStretch(1)
        self.quran_label = guiTools.QNavigableLabel("إعدادات البحث لعارض القرآن الكريم")
        self.quran_label.setFont(font)
        self.quran_label.setFocusPolicy(qt2.Qt.FocusPolicy.StrongFocus)
        self.quran_label.setAlignment(qt2.Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(self.quran_label)
        self.quran_tashkeel_checkbox = qt.QCheckBox("تجاهل التشكيل")
        self.quran_tashkeel_checkbox.setFont(font)
        self.quran_tashkeel_checkbox.setChecked(settings_handler.get("quran_search", "ignore_tashkeel") != "False")
        layout.addWidget(self.quran_tashkeel_checkbox, alignment=qt2.Qt.AlignmentFlag.AlignCenter)
        self.quran_hamza_checkbox = qt.QCheckBox("تجاهل الهمزات")
        self.quran_hamza_checkbox.setFont(font)
        self.quran_hamza_checkbox.setChecked(settings_handler.get("quran_search", "ignore_hamza") != "False")
        layout.addWidget(self.quran_hamza_checkbox, alignment=qt2.Qt.AlignmentFlag.AlignCenter)
        self.quran_symbols_checkbox = qt.QCheckBox("تجاهل الرموز والعلامات")
        self.quran_symbols_checkbox.setFont(font)
        self.quran_symbols_checkbox.setChecked(settings_handler.get("quran_search", "ignore_symbols") != "False")
        layout.addWidget(self.quran_symbols_checkbox, alignment=qt2.Qt.AlignmentFlag.AlignCenter)
        layout.addSpacing(15)
        self.researcher_label = guiTools.QNavigableLabel("إعدادات البحث لتبويبة الباحث في القرآن والأحاديث")
        self.researcher_label.setFont(font)
        self.researcher_label.setFocusPolicy(qt2.Qt.FocusPolicy.StrongFocus)
        self.researcher_label.setAlignment(qt2.Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(self.researcher_label)
        self.researcher_tashkeel_checkbox = qt.QCheckBox("تجاهل التشكيل")
        self.researcher_tashkeel_checkbox.setFont(font)
        self.researcher_tashkeel_checkbox.setChecked(settings_handler.get("researcher_search", "ignore_tashkeel") != "False")
        layout.addWidget(self.researcher_tashkeel_checkbox, alignment=qt2.Qt.AlignmentFlag.AlignCenter)
        self.researcher_hamza_checkbox = qt.QCheckBox("تجاهل الهمزات")
        self.researcher_hamza_checkbox.setFont(font)
        self.researcher_hamza_checkbox.setChecked(settings_handler.get("researcher_search", "ignore_hamza") != "False")
        layout.addWidget(self.researcher_hamza_checkbox, alignment=qt2.Qt.AlignmentFlag.AlignCenter)
        self.researcher_symbols_checkbox = qt.QCheckBox("تجاهل الرموز والعلامات")
        self.researcher_symbols_checkbox.setFont(font)
        self.researcher_symbols_checkbox.setChecked(settings_handler.get("researcher_search", "ignore_symbols") != "False")
        layout.addWidget(self.researcher_symbols_checkbox, alignment=qt2.Qt.AlignmentFlag.AlignCenter)
        layout.addStretch(1)
