import PyQt6.QtWidgets as qt
import PyQt6.QtCore as qt2
import PyQt6.QtGui as qt1
from guiTools import speak
from .utils import play_station_by_name


class brotcasts_of_reciters(qt.QWidget):
    def __init__(self, audio_output_instance, parent_widget):
        super().__init__()
        self.audio_output = audio_output_instance
        self.parent_widget = parent_widget
        style_sheet = "QListWidget::item { font-weight: bold; font-size: 12pt; }"
        self.list_of_reciters = qt.QListWidget()
        self.list_of_reciters.setSpacing(3)
        self.list_of_reciters.setStyleSheet(style_sheet)
        self.list_of_reciters.itemActivated.connect(self.play)
        self.list_of_reciters.setFocusPolicy(qt2.Qt.FocusPolicy.StrongFocus)
        self.list_of_reciters.setContextMenuPolicy(qt2.Qt.ContextMenuPolicy.CustomContextMenu)
        self.list_of_reciters.customContextMenuRequested.connect(self.on_context_menu)
        self.list_of_reciters.addItem("إذاعة القُراء")
        self.list_of_reciters.addItem("القارء أبو بكر الشاطري")
        self.list_of_reciters.addItem("القارئ إدريس أبكر")
        self.list_of_reciters.addItem("القارئ سعود الشريم")
        self.list_of_reciters.addItem("القارئ صلاح البدير")
        self.list_of_reciters.addItem("القارئ عبد الباسط عبد الصمد")
        self.list_of_reciters.addItem("القارئ عبد الرحمن السديس")
        self.list_of_reciters.addItem("القارئ ماهر المعيقلي")
        self.list_of_reciters.addItem("القارئ محمود خليل الحُصَري")
        self.list_of_reciters.addItem("القارئ محمود خليل الحُصَري القرآن بالتحقيق")
        self.list_of_reciters.addItem("القارئ محمود علي البنا القرآن بالتحقيق")
        self.list_of_reciters.addItem("مشاري راشد")
        self.list_of_reciters.addItem("القارئ مصطفى رعد العزاوي")
        self.list_of_reciters.addItem("القارئ مصطفى اللاهونِي")
        self.list_of_reciters.addItem("القارئ يحيى حوا")
        self.list_of_reciters.addItem("القارئ يوسف بن نوح")
        self.list_of_reciters.addItem("القارئ أحمد خضر الطرابلسي- رواية قالون عن نافع")
        self.list_of_reciters.addItem("القارئ طارق دعوب- رواية قالون عن نافع")
        self.list_of_reciters.addItem("القارئ عبد الباسط عبد الصمد- رواية ورش عن نافع")
        self.list_of_reciters.addItem("القارئ محمد عبد الكريم رواية ورش عن نافع من طريق أبي بكر الأصبهاني")
        self.list_of_reciters.addItem("القارئ\xa0 محمد عبد الحكيم قِراءة ابن كثير")
        self.list_of_reciters.addItem("القارئ الفاتح محمد الزُبَيْري- رواية الدُوري عن أبي عمرو")
        self.list_of_reciters.addItem("القارئ مفتاح السلطني- رواية الدُوري عن أبي عمرو")
        self.list_of_reciters.addItem("القارئ مفتاح السلطني- رواية ابن ذكوان عن ابن عامر")
        self.list_of_reciters.addItem("القارئ محمد عبد الحكيم سعيد- رواية الدُوري عن الكِسائي")
        self.list_of_reciters.addItem("القارئ عبد الرشيد صوفي- رواية خلف عن حمزة")
        self.list_of_reciters.addItem("القارئ محمود الشيمي- رواية الدُوري عن الكِسائي")
        self.list_of_reciters.addItem("القارئ مفتاح السلطني- رواية الدُوري عن الكِسائي")
        self.list_of_reciters.addItem("القارئ ياسر المزروعي قِراءة يعقوب")
        self.list_of_reciters.addItem("القارئ الشيخ العيون الكوشي - ورش عن نافع")
        self.list_of_reciters.addItem("إذاعة أحمد الطرابلسي")
        self.list_of_reciters.addItem("إذاعة أحمد عامر")
        self.list_of_reciters.addItem("إذاعة ابراهيم الدوسري")
        self.list_of_reciters.addItem("إذاعة الدوكالي محمد العالم")
        self.list_of_reciters.addItem("إذاعة جمعان العصيمي")
        self.list_of_reciters.addItem("إذاعة خالد المهنا")
        self.list_of_reciters.addItem("إذاعة عادل الكلباني")
        self.list_of_reciters.addItem("إذاعة عبدالرحمن الماجد")
        self.list_of_reciters.addItem("إذاعة عبدالله الكندري")
        self.list_of_reciters.addItem("إذاعة علي جابر")
        self.list_of_reciters.addItem("إذاعة علي حجاج السويسي")
        self.list_of_reciters.addItem("إذاعة عماد زهير حافظ")
        self.list_of_reciters.addItem("إذاعة عمر القزابري")
        self.list_of_reciters.addItem("إذاعة فارس عباد")
        self.list_of_reciters.addItem("إذاعة ماهر المعيقلي")
        self.list_of_reciters.addItem("إذاعة ماهر شخاشيرو")
        self.list_of_reciters.addItem("إذاعة محمد أيوب")
        self.list_of_reciters.addItem("إذاعة محمد الطبلاوي")
        self.list_of_reciters.addItem("إذاعة محمد اللحيدان")
        self.list_of_reciters.addItem("إذاعة محمد جبريل")
        self.list_of_reciters.addItem("إذاعة محمد رشاد الشريف")
        self.list_of_reciters.addItem("إذاعة محمد صالح عالم شاه")
        self.list_of_reciters.addItem("إذاعة محمد صديق المنشاوي - المرتل")
        self.list_of_reciters.addItem("إذاعة محمد صديق المنشاوي - المجود")
        self.list_of_reciters.addItem("إذاعة محمد عبدالكريم")
        self.list_of_reciters.addItem("إذاعة محمود الرفاعي")
        self.list_of_reciters.addItem("إذاعة محمود خليل الحصري - المرتل")
        self.list_of_reciters.addItem("إذاعة محمود خليل الحصري - رواية ورش عن نافع")
        self.list_of_reciters.addItem("إذاعة محمود علي البنا - المرتل")
        self.list_of_reciters.addItem("إذاعة مشاري العفاسي")
        self.list_of_reciters.addItem("إذاعة مصطفى إسماعيل")
        self.list_of_reciters.addItem("إذاعة مصطفى اللاهوني")
        self.list_of_reciters.addItem("إذاعة معيض الحارثي")
        self.list_of_reciters.addItem("إذاعة موسى بلال")
        self.list_of_reciters.addItem("إذاعة ناصر القطامي")
        self.list_of_reciters.addItem("إذاعة نبيل الرفاعي")
        self.list_of_reciters.addItem("إذاعة نعمة الحسان")
        self.list_of_reciters.addItem("إذاعة هاني الرفاعي")
        self.list_of_reciters.addItem("إذاعة وليد النائحي")
        self.list_of_reciters.addItem("إذاعة ياسر الدوسري")
        self.list_of_reciters.addItem("إذاعة ياسر القرشي")
        self.list_of_reciters.addItem("إذاعة يوسف الشويعي")
        self.list_of_reciters.addItem("إذاعة أحمد الحواشي")
        self.list_of_reciters.addItem("إذاعة أحمد العجمي")
        self.list_of_reciters.addItem("إذاعة أحمد خليل شاهين")
        self.list_of_reciters.addItem("إذاعة أحمد ديبان")
        self.list_of_reciters.addItem("إذاعة أحمد صابر")
        self.list_of_reciters.addItem("إذاعة أحمد نعينع")
        self.list_of_reciters.addItem("إذاعة أكرم العلاقمي")
        self.list_of_reciters.addItem("إذاعة إبراهيم الأخضر")
        self.list_of_reciters.addItem("إذاعة إدريس أبكر")
        self.list_of_reciters.addItem("إذاعة الزين محمد أحمد")
        self.list_of_reciters.addItem("إذاعة العيون الكوشي")
        self.list_of_reciters.addItem("إذاعة الفتاوى العامة")
        self.list_of_reciters.addItem("إذاعة القارئ ياسين")
        self.list_of_reciters.addItem("إذاعة بندر بليلة")
        self.list_of_reciters.addItem("إذاعة توفيق الصايغ")
        self.list_of_reciters.addItem("إذاعة جمال شاكر عبدالله")
        self.list_of_reciters.addItem("إذاعة خالد الجليل")
        self.list_of_reciters.addItem("إذاعة خالد القحطاني")
        self.list_of_reciters.addItem("إذاعة خالد عبدالكافي")
        self.list_of_reciters.addItem("إذاعة خليفة الطنيجي")
        self.list_of_reciters.addItem("إذاعة زكي داغستاني")
        self.list_of_reciters.addItem("إذاعة سعود الشريم")
        self.list_of_reciters.addItem("إذاعة سهل ياسين")
        self.list_of_reciters.addItem("إذاعة سيد رمضان")
        self.list_of_reciters.addItem("إذاعة شيخ أبو بكر الشاطري")
        self.list_of_reciters.addItem("إذاعة شيرزاد عبدالرحمن طاهر")
        self.list_of_reciters.addItem("إذاعة صابر عبدالحكم")
        self.list_of_reciters.addItem("إذاعة صلاح الهاشم")
        self.list_of_reciters.addItem("إذاعة صلاح بو خاطر")
        self.list_of_reciters.addItem("إذاعة عادل ريان")
        self.list_of_reciters.addItem("إذاعة عبدالبارئ الثبيتي")
        self.list_of_reciters.addItem("إذاعة عبدالبارئ محمد")
        self.list_of_reciters.addItem("إذاعة عبدالباسط عبدالصمد - المجود")
        self.list_of_reciters.addItem("إذاعة عبدالباسط عبدالصمد - رواية ورش عن نافع")
        self.list_of_reciters.addItem("إذاعة عبدالباسط عبدالصمد - المرتل")
        self.list_of_reciters.addItem("إذاعة عبدالرحمن السديس")
        self.list_of_reciters.addItem("إذاعة عبدالرحمن الشحات")
        self.list_of_reciters.addItem("إذاعة عبدالرشيد صوفي - رواية السوسي عن أبي عمرو")
        self.list_of_reciters.addItem("إذاعة عبدالعزيز الأحمد")
        self.list_of_reciters.addItem("إذاعة عبدالله الخلف")
        self.list_of_reciters.addItem("إذاعة عبدالله المطرود")
        self.list_of_reciters.addItem("إذاعة عبدالله الموسى")
        self.list_of_reciters.addItem("إذاعة عبدالله بصفر")
        self.list_of_reciters.addItem("إذاعة عبدالله خياط")
        self.list_of_reciters.addItem("إذاعة عبدالله عواد الجهني")
        self.list_of_reciters.addItem("إذاعة عبدالمحسن الحارثي")
        self.list_of_reciters.addItem("إذاعة عبدالمحسن العبيكان")
        self.list_of_reciters.addItem("إذاعة عبدالمحسن القاسم")
        self.list_of_reciters.addItem("إذاعة عبدالهادي أحمد كناكري")
        self.list_of_reciters.addItem("إذاعة عبدالودود حنيف")
        self.list_of_reciters.addItem("إذاعة علي الحذيفي")
        self.list_of_reciters.addItem("إذاعة علي بن عبدالرحمن الحذيفي")
        self.list_of_reciters.addItem("إذاعة ماجد الزامل")
        self.list_of_reciters.addItem("إذاعة محمد أيوب - قراءة مميزة")
        self.list_of_reciters.addItem("إذاعة محمد الأمين قنيوة")
        self.list_of_reciters.addItem("إذاعة محمد عثمان خان")
        self.list_of_reciters.addItem("إذاعة ناصر العصفور")
        self.list_of_reciters.addItem("إذاعة ناصر الماجد")
        self.list_of_reciters.addItem("إذاعة نداء الإسلام - مكة المكرمة")
        self.list_of_reciters.addItem("إذاعة هيثم الجدعاني")
        self.list_of_reciters.addItem("أحمد طالب بن حميد")
        self.list_of_reciters.addItem("إذاعة محمد أبوسنينة")
        self.list_of_reciters.addItem("بدر التركي")
        self.list_of_reciters.addItem("حاتم فريد الواعر")
        self.list_of_reciters.addItem("صالح الهبدان")
        self.list_of_reciters.addItem("عبدالعزيز سحيم")
        self.list_of_reciters.addItem("عبدالله البعيجان")
        self.list_of_reciters.addItem("هزاع البلوشي")
        layout = qt.QVBoxLayout(self)
        layout.addWidget(self.list_of_reciters)
        self.volume_up_shortcut = qt1.QShortcut(qt1.QKeySequence("Shift+Up"), self.list_of_reciters)
        self.volume_up_shortcut.activated.connect(self.increase_volume)
        self.volume_down_shortcut = qt1.QShortcut(qt1.QKeySequence("Shift+Down"), self.list_of_reciters)
        self.volume_down_shortcut.activated.connect(self.decrease_volume)

    def on_context_menu(self, pos):
        item = self.list_of_reciters.itemAt(pos)
        if not item:
            item = self.list_of_reciters.currentItem()
        if item:
            self.parent_widget.toggle_station_favorite(item.text())

    def play(self):
        selected_item = self.list_of_reciters.currentItem()
        if not selected_item: return
        play_station_by_name(selected_item.text())

    def increase_volume(self):
        if self.audio_output:
            current_volume = self.audio_output.volume()
            new_volume = min(1.0, current_volume + 0.1)
            self.audio_output.setVolume(new_volume)
            volume_percent = int(new_volume * 100)
            speak(f"نسبة الصوت {volume_percent}")
            self.parent_widget.aud.setText(f"نسبة الصوت: {volume_percent}%")
            self.parent_widget.volume_timer.start(1000)

    def decrease_volume(self):
        if self.audio_output:
            current_volume = self.audio_output.volume()
            new_volume = max(0.0, current_volume - 0.1)
            self.audio_output.setVolume(new_volume)
            volume_percent = int(new_volume * 100)
            speak(f"نسبة الصوت {volume_percent}")
            self.parent_widget.aud.setText(f"نسبة الصوت: {volume_percent}%")
            self.parent_widget.volume_timer.start(1000)
