import guiTools, pyperclip, winsound, functions, re, os, settings, requests, shutil
import ujson as json
import PyQt6.QtWidgets as qt
import PyQt6.QtGui as qt1
import PyQt6.QtCore as qt2
from PyQt6.QtMultimedia import QAudioOutput, QMediaPlayer
from gui.quranViewer import QuranViewer
from gui.tafaseerViewer import TafaseerViewer
from gui.translationViewer import translationViewer
from gui.changeReciter import ChangeReciter
from .search_worker import DownloadThread, SearchModeDialog, SearchThread, RemainingThread


class ResearcherContextMenuMixin:
    def OnContextMenu(self):
        self.pause_for_action()
        cursor = self.results.textCursor()
        line_number = cursor.blockNumber() + 1
        metadata = self.search_metadata.get(line_number)
        menu = guiTools.QCustomContextMenu("الخيارات", self)
        bold_font = qt1.QFont()
        bold_font.setBold(True)
        menu.setFont(bold_font)
        if metadata:
            if isinstance(metadata, dict) and metadata.get("type") == "hadith":
                goto_hadith_action = qt1.QAction(f"الذهاب إلى كتاب {metadata['book_name']}", self)
                goto_hadith_action.setShortcut("Ctrl+G")
                goto_hadith_action.triggered.connect(lambda: self.go_to_hadith(metadata))
                menu.addAction(goto_hadith_action)
                menu.addSeparator()
                copy_all = qt1.QAction("نسخ النص كاملا", self)
                copy_all.setShortcut("Ctrl+A")
                copy_all.triggered.connect(self.copy_text)
                menu.addAction(copy_all)
                copy_selected = qt1.QAction("نسخ النص المحدد", self)
                copy_selected.setShortcut("Ctrl+C")
                copy_selected.triggered.connect(self.copy_line)
                menu.addAction(copy_selected)
            else:
                ayah_menu = guiTools.QCustomContextMenu("خيارات الآية", self)
                ayah_menu.setFont(bold_font)
                speed_menu = ayah_menu.addMenu("سرعة التشغيل")
                speed_menu.setFont(bold_font)
                current_speed = self.load_speed()
                speeds = [0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2.75, 3.0]
                for s in speeds:
                    action = speed_menu.addAction(f"{s}x")
                    action.setCheckable(True)
                    action.setChecked(abs(current_speed - s) < 0.01)
                    action.triggered.connect(lambda checked, val=s: self.change_speed(val))
                play_action = qt1.QAction("تشغيل الآية", self)
                play_action.setShortcut(qt1.QKeySequence(qt2.Qt.Key.Key_Space))
                play_action.triggered.connect(lambda: self.start_playback(metadata))
                ayah_menu.addAction(play_action)
                change_reciter_action = qt1.QAction("تغيير القارئ", self)
                change_reciter_action.setShortcut("Ctrl+Shift+R")
                change_reciter_action.triggered.connect(self.on_change_reciter_requested)
                ayah_menu.addAction(change_reciter_action)
                goto_surah_action = qt1.QAction(f"الذهاب إلى سورة {metadata['surah_name']}", self)
                goto_surah_action.setShortcut("Ctrl+G")
                goto_surah_action.triggered.connect(lambda: self.go_to_surah(metadata))
                ayah_menu.addAction(goto_surah_action)
                tafseer_action = qt1.QAction("تفسير الآية", self)
                tafseer_action.setShortcut("Ctrl+T")
                tafseer_action.triggered.connect(lambda: self.show_tafseer(metadata))
                ayah_menu.addAction(tafseer_action)
                translation_action = qt1.QAction("ترجمة الآية", self)
                translation_action.setShortcut("Ctrl+L")
                translation_action.triggered.connect(lambda: self.show_translation(metadata))
                ayah_menu.addAction(translation_action)
                iarab_menu = ayah_menu.addMenu("إعراب الآية: Ctrl+I")
                iarab_menu.setFont(bold_font)
                simplified_iarab_action = qt1.QAction("إعراب مبسط", self)
                simplified_iarab_action.triggered.connect(lambda: self.show_simplified_iarab(metadata))
                iarab_menu.addAction(simplified_iarab_action)
                detailed_iarab_action = qt1.QAction("إعراب مفصل", self)
                detailed_iarab_action.triggered.connect(lambda: self.show_detailed_iarab(metadata))
                iarab_menu.addAction(detailed_iarab_action)
                analytical_iarab_action = qt1.QAction("إعراب تحليلي", self)
                analytical_iarab_action.triggered.connect(lambda: self.show_analytical_iarab(metadata))
                iarab_menu.addAction(analytical_iarab_action)
                qiraat_action = qt1.QAction("قراءات الآية", self)
                qiraat_action.setShortcut("Ctrl+E")
                qiraat_action.triggered.connect(lambda: self.show_qiraat(metadata))
                ayah_menu.addAction(qiraat_action)
                meanings_action = qt1.QAction("معاني كلمات الآية", self)
                meanings_action.setShortcut("Ctrl+U")
                meanings_action.triggered.connect(lambda: self.show_meanings(metadata))
                ayah_menu.addAction(meanings_action)
                sarf_action = qt1.QAction("صرف كلمات الآية", self)
                sarf_action.setShortcut("Ctrl+K")
                sarf_action.triggered.connect(lambda: self.show_sarf(metadata))
                ayah_menu.addAction(sarf_action)
                tanzil_action = qt1.QAction("أسباب نزول الآية", self)
                tanzil_action.setShortcut("Ctrl+R")
                tanzil_action.triggered.connect(lambda: self.show_tanzil(metadata))
                ayah_menu.addAction(tanzil_action)
                info_action = qt1.QAction("معلومات الآية", self)
                info_action.setShortcut("Ctrl+F")
                info_action.triggered.connect(lambda: self.show_ayah_info(metadata))
                ayah_menu.addAction(info_action)
                save_ayah_action = qt1.QAction("حفظ الآية", self)
                save_ayah_action.setShortcut("Ctrl+H")
                save_ayah_action.triggered.connect(lambda: self.save_ayah(metadata))
                ayah_menu.addAction(save_ayah_action)
                menu.addMenu(ayah_menu)
                menu.addSeparator()
                text_menu = guiTools.QCustomContextMenu("خيارات النص", self)
                text_menu.setFont(bold_font)
                copy_all = qt1.QAction("نسخ النص كاملا", self)
                copy_all.setShortcut("Ctrl+A")
                copy_all.triggered.connect(self.copy_text)
                text_menu.addAction(copy_all)
                copy_selected = qt1.QAction("نسخ النص المحدد", self)
                copy_selected.setShortcut("Ctrl+C")
                copy_selected.triggered.connect(self.copy_line)
                text_menu.addAction(copy_selected)
                menu.addMenu(text_menu)
        else:
            copy_all = qt1.QAction("نسخ النص كاملا", self)
            copy_all.setShortcut("Ctrl+A")
            copy_all.triggered.connect(self.copy_text)
            menu.addAction(copy_all)
            copy_selected = qt1.QAction("نسخ النص المحدد", self)
            copy_selected.setShortcut("Ctrl+C")
            copy_selected.triggered.connect(self.copy_line)
            menu.addAction(copy_selected)
        menu.exec(qt1.QCursor.pos())
        self.resume_after_action()
